services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    ports:
      - "8543:8000"  # Zugriff über localhost:8543
    volumes:
      - chroma-data:/data
    environment:
      - CHROMA_TELEMETRY_ENABLED=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v2/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - backend

  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP UI (http://localhost:7474)
      - "7687:7687"  # Bolt-Protokoll (für Neomodel etc.)
    volumes:
      - neo4j-data:/data
    environment:
      - NEO4J_AUTH=neo4j/password123
    restart: unless-stopped
    networks:
      - backend

volumes:
  chroma-data:
    driver: local
  neo4j-data:
    driver: local

networks:
  backend:
    driver: bridge
